name: water_delivery
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  animations: ^2.0.8
  auto_route: ^7.8.3
  carousel_slider: ^4.2.1
  collection: ^1.17.2
  expandable_page_view: ^1.0.17
  flutter:
    sdk: flutter
  flutter_advanced_segment: ^3.0.2
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.7
  mask_text_input_formatter: ^2.5.0
  neumorphic_ui: ^1.0.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  auto_route_generator: ^7.3.1

flutter_gen:
  output: lib/generated/

  integrations:
    flutter_svg: true  

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
